trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'gcr_teste'
        repository: 'estudo-ci-cd/ApiEstudo'
        command: buildAndPush
        dockerfile: 'ApiEstudo/Dockerfile'
        tags: |
          $(tag)
    - task: KubernetesManifest@0
      displayName: Publish an image to GKE
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'clbueno-1'
        namespace: 'ApiEstudo'
        manifests: 'deployment.yaml'