apiVersion: v1
kind: Service
metadata:
  name: apiestudo
spec:
  ports:
  - port: 81
    targetPort: 81
    protocol: TCP
    name: http
  selector:
    app: apiestudo
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apiestudo
spec:
  backend:
    serviceName: apiestudo
    servicePort: 81

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiestudo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: apiestudo
    spec:
      containers:
      - name: apiestudo
        image: ApiEstudo
        ports:
          - containerPort: 81
        
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: 200m
            memory: 2Gi