apiVersion: v1
kind: Service
metadata:
  name: ApiEstudo
spec:
  ports:
  - port: 81
    targetPort: 81
    protocol: TCP
    name: http
  selector:
    app: apiestudo
  type: NodePort


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiestudo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apiestudo
    spec:
      containers:
      - name: apiestudo
        image: ApiEstudo
        ports:
          - containerPort: 81
        livenessProbe:      # Used by deployment controller
          httpGet:
            path: /
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:     # Used by Ingress/GCLB
          httpGet:
            path: /
            port: 81
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 768Mi