apiVersion: v1
kind: Service
metadata:
  name: apiestudo
spec:
  ports:
  - port: 81
  - targetPort: 81
    protocol: TCP
    name: http
  selector:
    app: apiestudo
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apiestudo
spec:
  backend:
    serviceName: apiestudo
    servicePort: 81

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiestudo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apiestudo
    spec:
      containers:
      - name: apiestudo
        image: estudo-ci-cd/ApiEstudo:107
        ports:
          - containerPort: 81
        livenessProbe:     
          httpGet:
            path: /
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:    
          httpGet:
            path: /
            port: 81
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 768Mi