apiVersion: v1
kind: Service
metadata:
  name: apiestudo
spec:
  ports:
  - port: 81
    targetPort: 81
    protocol: TCP
    name: http
  selector:
    app: apiestudo
  type: NodePort


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiestudo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: apiestudo
    spec:
      containers:
      - name: apiestudo
        image: ApiEstudo
        ports:
          - containerPort: 81
        livenessProbe:     
          httpGet:
            path: /
            port: 81
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:    
          httpGet:
            path: /
            port: 81
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: 400m
            memory: 2Gi