- task: CmdLine@1
      displayName: Lock File Mnifest
      inputs:
        filename: /bin/bash
        arguments: '-c "awk ''{gsub(\"ApiEstudo\", \"gcr.io/$(DockerImageName):$(Build.BuildId)\", $0); print}'' deployment.yaml > $(build.artifactstagingdirectory)/deployment.yaml"'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
       PathtoPublish: '$(build.artifactstagingdirectory)'

    - task: KubernetesManifest@0
      displayName: Publish an image to GKE
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'clbueno-1'
        namespace: 'default'
        manifests: '$(build.artifactstagingdirectory)'